### PR TITLE
Add docstring example to FAQ

### PR DESCRIPTION
**Pull request by lilyminium**
Related to #58 

Changes:
- Adds example to FAQ

I tried to include relevant terms I used when googling.

### CODE REVIEW

**Review by mansenfranzen — CHANGES_REQUESTED** [review]
Thanks for adding the PR! This is the first documentation related PR by a contributor 🚀 🥳.

I added some minor modifications to your documentation. I hope you agree with those changes.

**Comment by mansenfranzen** [comment]
@all-contributors please add @lilyminium for doc

**Comment by mansenfranzen** [comment]
@all-contributors please add @lilyminium for doc, content

**Comment by lilyminium** [comment]
@mansenfranzen yeah they looked good, thanks! I just added an 's' in 4fa9eb722ab3a646b4b3d5e622af17fde6c6b2bf :)

**Comment by mansenfranzen** [comment]
Thanks for contributing @lilyminium

**Pull request merged**
